[package]
name = "hub"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { workspace = true }
service-abi = { path = "../../03-driver/service-abi" }
smallvec = { workspace = true }
world = { path = "../world" }
