[package]
name = "services-kernel"
version = "0.1.0"
edition = "2021"

[dependencies]
hub = { path = "../../05-app-loop/hub" }
smallvec = { workspace = true }
gbx-frame = { path = "../../05-app-loop/gbx-frame" }
services-common = { path = "../../03-driver/services-common" }
