# Nextest configuration for tight test discipline
# Two-bucket approach: fast (default, PR runs) and slow (ignored, nightly/on-demand)

# Fast profile (default for PR suite)
# - Runs all non-ignored tests
# - Target: ≤100ms per test
# - Warning threshold: ~200ms (tests exceeding this should be moved to slow)
# - Hard safety cap: 20s (should never be hit by properly classified tests)
[profile.fast]
status-level = "fail"
fail-fast = true
retries = 0

# Warn when tests exceed 200ms (reclassification threshold)
# terminate-after is number of periods (100 periods * 200ms = 20s hard cap)
[profile.fast.slow-timeout]
period = "200ms"
terminate-after = 100

# Slow profile (ignored-only, for nightly/manual runs)
# - Runs only #[ignore] tests
# - Allows longer execution for loom exploration (60s hard cap)
# - Less strict on failure reporting for exploratory/deep tests
[profile.slow]
status-level = "pass"
fail-fast = false
retries = 0

# terminate-after is 1 period (1 * 60s = 60s hard cap for loom tests)
[profile.slow.slow-timeout]
period = "60s"
terminate-after = 1
