[package]
name = "transport"
version = "0.1.0"
edition = "2021"

[dependencies]
rkyv = { version = "0.7", features = ["validation"] }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
memmap2 = "0.9"

[dev-dependencies]
rand = { version = "0.8", features = ["std"] }
