[package]
name = "kernel-core"
version = "0.1.0"
edition = "2021"

[dependencies]

[dev-dependencies]
proptest = "1.4"
testdata = { path = "../../testdata" }
safeboy = "0.2"
anyhow = "1"
pretty_assertions = "1"
