name: cloud-parity

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  claude-approx-parity:
    runs-on: ubuntu-latest
    env:
      SKIP_TESTROMS: "1"
      GBX_SKIP_TESTROMS: "1"
    steps:
      - uses: actions/checkout@v4
      - name: Bootstrap (approximate Claude container)
        run: bash scripts/cloud/setup.sh
      - name: Parity suite
        run: bash scripts/tasks/run.sh ci-parity
