name: cloud-parity

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  codex-universal-parity:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/openai/codex-universal:latest
    steps:
      - uses: actions/checkout@v4
      - name: Bootstrap (toolchains, npm, browser)
        run: bash scripts/cloud/setup.sh
      - name: Parity suite (fmt, lint, build native+wasm, nextest fast, wasm light)
        run: bash scripts/tasks/run.sh ci-parity

  claude-approx-parity:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Bootstrap (approximate Claude container)
        run: bash scripts/cloud/setup.sh
      - name: Parity suite
        run: bash scripts/tasks/run.sh ci-parity
